export const SET_DASH_BODY_LOADING = 'SET_DASH_BODY_LOADING'
export const GET_DASH_BODY_LOADING = 'GET_DASH_BODY_LOADING'
export const SET_DASH_FOOTER = 'SET_DASH_FOOTER'
export const GET_DASH_FOOTER = 'GET_DASH_FOOTER'
