export const GET_WORKII_INDEX_DISP = 'GET_WORKII_INDEX_DISP'
export const GET_WORKII_DETAIL_DISP = 'GET_WORKII_DETAIL_DISP'
export const SET_WORKII_TOGGLE_PAGE = 'SET_WORKII_TOGGLE_PAGE'

export const SET_WORKII = 'SET_WORKII'
export const GET_WORKII = 'GET_WORKII'
export const RECEIVED_WORKII = 'RECEIVED_WORKII'

export const SET_WORKII_DETAIL = 'SET_WORKII_DETAIL'
export const GET_WORKII_DETAIL = 'GET_WORKII_DETAIL'
export const RECEIVED_WORKII_DETAIL = 'RECEIVED_WORKII_DETAIL'
