export const GET_WORKIII_INDEX_DISP = 'GET_WORKIII_INDEX_DISP'
export const GET_WORKIII_DETAIL_DISP = 'GET_WORKIII_DETAIL_DISP'
export const SET_WORKIII_TOGGLE_PAGE = 'SET_WORKIII_TOGGLE_PAGE'

export const SET_WORKIII = 'SET_WORKIII'
export const GET_WORKIII = 'GET_WORKIII'
export const RECEIVED_WORKIII = 'RECEIVED_WORKIII'

export const SET_WORKIII_DETAIL = 'SET_WORKIII_DETAIL'
export const GET_WORKIII_DETAIL = 'GET_WORKIII_DETAIL'
export const RECEIVED_WORKIII_DETAIL = 'RECEIVED_WORKIII_DETAIL'
