export const GET_PERSONALII_INDEX_DISP = 'GET_PERSONALII_INDEX_DISP'
export const GET_PERSONALII_DETAIL_DISP = 'GET_PERSONALII_DETAIL_DISP'
export const SET_PERSONALII_TOGGLE_PAGE = 'SET_PERSONALII_TOGGLE_PAGE'

export const SET_PERSONALII = 'SET_PERSONALII'
export const GET_PERSONALII = 'GET_PERSONALII'
export const RECEIVED_PERSONALII = 'RECEIVED_PERSONALII'

export const SET_PERSONALII_DETAIL = 'SET_PERSONALII_DETAIL'
export const GET_PERSONALII_DETAIL = 'GET_PERSONALII_DETAIL'
export const RECEIVED_PERSONALII_DETAIL = 'RECEIVED_PERSONALII_DETAIL'
