export const GET_HOME_INDEX_DISP = 'GET_HOME_INDEX_DISP'
export const GET_HOME_DETAIL_DISP = 'GET_HOME_DETAIL_DISP'
export const SET_HOME_TOGGLE_PAGE = 'SET_HOME_TOGGLE_PAGE'

export const SET_HOME = 'SET_HOME'
export const GET_HOME = 'GET_HOME'
export const RECEIVED_HOME = 'RECEIVED_HOME'

export const SET_HOME_DETAIL = 'SET_HOME_DETAIL'
export const GET_HOME_DETAIL = 'GET_HOME_DETAIL'
export const RECEIVED_HOME_DETAIL = 'RECEIVED_HOME_DETAIL'
