export const GET_PERSONALI_INDEX_DISP = 'GET_PERSONALI_INDEX_DISP'
export const GET_PERSONALI_DETAIL_DISP = 'GET_PERSONALI_DETAIL_DISP'
export const SET_PERSONALI_TOGGLE_PAGE = 'SET_PERSONALI_TOGGLE_PAGE'

export const SET_PERSONALI = 'SET_PERSONALI'
export const GET_PERSONALI = 'GET_PERSONALI'
export const RECEIVED_PERSONALI = 'RECEIVED_PERSONALI'

export const SET_PERSONALI_DETAIL = 'SET_PERSONALI_DETAIL'
export const GET_PERSONALI_DETAIL = 'GET_PERSONALI_DETAIL'
export const RECEIVED_PERSONALI_DETAIL = 'RECEIVED_PERSONALI_DETAIL'
