export const GET_PERSONALIII_INDEX_DISP = 'GET_PERSONALIII_INDEX_DISP'
export const GET_PERSONALIII_DETAIL_DISP = 'GET_PERSONALIII_DETAIL_DISP'
export const SET_PERSONALIII_TOGGLE_PAGE = 'SET_PERSONALIII_TOGGLE_PAGE'

export const SET_PERSONALIII = 'SET_PERSONALIII'
export const GET_PERSONALIII = 'GET_PERSONALIII'
export const RECEIVED_PERSONALIII = 'RECEIVED_PERSONALIII'

export const SET_PERSONALIII_DETAIL = 'SET_PERSONALIII_DETAIL'
export const GET_PERSONALIII_DETAIL = 'GET_PERSONALIII_DETAIL'
export const RECEIVED_PERSONALIII_DETAIL = 'RECEIVED_PERSONALIII_DETAIL'
